[package]
name = "rwc"
version = "0.1.0"
edition = "2021"

# Reduce the size of binary file
[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
incremental = false

[dependencies]
tokio = {version = "*", features = ["rt", "rt-multi-thread", "macros", "time", "fs", "io-util"]}
tokio-stream = "*"
futures = "*"
clap = {version = "*", features = ["derive"]}
clap_complete = "*"
indicatif = "*"
anyhow = "*"
prettytable-rs = "*"

[build-dependencies]
clap = {version = "*", features = ["derive"]}
clap_complete = "*"
