[package]
name = "rwc"
description = "A GNU/wc clone written in rust, which is super faster when reading a large of big files"
version = "0.3.0"
authors = ["jedsek <jedsek@qq.com>"]
edition = "2021"
readme = "README.md"

documentation = "https://github.com/jedsek/rust-wc"
homepage = "https://github.com/jedsek/rust-wc"
repository = "https://github.com/jedsek/rust-wc"

keywords = ["wc", "command-line", "rust-wc", "rwc"]
categories = ["command-line-utilities", "unix", "tools", "wc"]
license = "MIT"

# Reduce the size of binary file
[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
incremental = false
strip = true

[dependencies]
clap = {version = "*", features = ["derive"]}
indicatif = "*"
prettytable-rs = {version = "*", default-features = false}
rayon = "*"
tap = "*"

[build-dependencies]
clap = {version = "*", features = ["derive"]}
clap_complete = "*"
