[package]
name = "rwc"
version = "0.1.0"
edition = "2021"

# Reduce the size of binary file
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
incremental = false
strip = true

[dependencies]
clap = {version = "*", features = ["derive"]}
indicatif = "*"
prettytable-rs = {version = "*", default-features = false}
rayon = "*"
tap = "*"
anyhow = "*"

[build-dependencies]
clap = {version = "*", features = ["derive"]}
clap_complete = "*"
