complete -c rwc -s b -l bytes -d 'Show the count of bytes'
complete -c rwc -s c -l chars -d 'Show the count of chars'
complete -c rwc -s w -l words -d 'Show the count of words'
complete -c rwc -s l -l lines -d 'Show the count of lines'
complete -c rwc -s L -l longest-line -d 'Show the length of the longest line'
complete -c rwc -s h -l help -d 'Print help information'
complete -c rwc -s V -l version -d 'Print version information'
