complete -c rwc -n "__fish_use_subcommand" -s b -l bytes -d 'Print the byte counts'
complete -c rwc -n "__fish_use_subcommand" -s c -l chars -d 'Print the character counts'
complete -c rwc -n "__fish_use_subcommand" -s w -l words -d 'Print the word counts'
complete -c rwc -n "__fish_use_subcommand" -s l -l lines -d 'Print the line counts'
complete -c rwc -n "__fish_use_subcommand" -s L -l longest-line -d 'Print the maximum line width (Chars)'
complete -c rwc -n "__fish_use_subcommand" -s h -l help -d 'Print help information'
complete -c rwc -n "__fish_use_subcommand" -s V -l version -d 'Print version information'
complete -c rwc -n "__fish_use_subcommand" -f -a "all" -d 'Enabled all available options'
complete -c rwc -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c rwc -n "__fish_seen_subcommand_from all" -s h -l help -d 'Print help information'
complete -c rwc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from help" -f -a "all" -d 'Enabled all available options'
complete -c rwc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
